name: 'Claude Code Review'
description: 'Automated code review using Claude API'
inputs:
  api-key:
    description: 'Claude API key'
    required: true
  github-token:
    description: 'GitHub token for posting comments'
    required: true
  file-patterns:
    description: 'Patterns of files to review (comma-separated)'
    required: false
    default: '*.js,*.ts,*.jsx,*.tsx'
  max-files:
    description: 'Maximum number of files to review per PR'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ github.action_path }}
    
    - name: Run Claude code review
      shell: bash
      run: node ${{ github.action_path }}/src/review.js
      env:
        CLAUDE_API_KEY: ${{ inputs.api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        FILE_PATTERNS: ${{ inputs.file-patterns }}
        MAX_FILES: ${{ inputs.max-files }}